import Image from "next/image";
import Link from "next/link";
import { PageShell } from "@/components/page-shell";
import { FootballDirectoryNav } from "@/components/football-directory-nav";
import { ACTIVE_SEASON_YEAR } from "@/config/season";
import { prisma } from "@/lib/prisma";
import { firstParam, resolveDirectoryCompetition, round } from "@/lib/football-directory";
import styles from "../football-data.module.css";

type Props={searchParams:Promise<{league?:string|string[];team?:string|string[];position?:string|string[];q?:string|string[]}>};
const positions=["ALL","GOALKEEPER","DEFENDER","MIDFIELDER","FORWARD"] as const;
const positionName=(p:string)=>({GOALKEEPER:"Kaleci",DEFENDER:"Defans",MIDFIELDER:"Orta saha",FORWARD:"Forvet",UNKNOWN:"Belirsiz"}[p]??"Tümü");

export default async function PlayersPage({searchParams}:Props){
 const params=await searchParams,competition=resolveDirectoryCompetition(params.league);const q=(firstParam(params.q)??"").trim();const requestedPosition=(firstParam(params.position)??"ALL").toUpperCase();const position=positions.includes(requestedPosition as typeof positions[number])?requestedPosition:"ALL";
 const season=await prisma.season.findFirst({where:{year:ACTIVE_SEASON_YEAR,league:{apiId:competition.apiId}},select:{id:true}});
 const matches=await prisma.match.findMany({where:{seasonId:season?.id??-1},select:{homeTeam:{select:{id:true,name:true,logoUrl:true}},awayTeam:{select:{id:true,name:true,logoUrl:true}}}});const teamMap=new Map<number,typeof matches[number]["homeTeam"]>();for(const m of matches){teamMap.set(m.homeTeam.id,m.homeTeam);teamMap.set(m.awayTeam.id,m.awayTeam)}const teams=[...teamMap.values()].sort((a,b)=>a.name.localeCompare(b.name,"tr"));
 const requestedTeam=Number.parseInt(firstParam(params.team)??"",10);const selectedTeam=teams.find(t=>t.id===requestedTeam)??teams[0]??null;
 const rows=selectedTeam&&season?await prisma.playerSeasonStatistic.findMany({where:{seasonId:season.id,teamId:selectedTeam.id,...(position!=="ALL"?{player:{position:position as "GOALKEEPER"|"DEFENDER"|"MIDFIELDER"|"FORWARD"}}:{}),...(q?{player:{name:{contains:q,mode:"insensitive"},...(position!=="ALL"?{position:position as "GOALKEEPER"|"DEFENDER"|"MIDFIELDER"|"FORWARD"}:{})}}:{})},orderBy:[{appearances:"desc"},{minutes:"desc"}],include:{player:{include:{injuries:{where:{actualReturnDate:null},orderBy:{createdAt:"desc"},take:1}}}}}):[];
 const allCount=selectedTeam&&season?await prisma.playerSeasonStatistic.count({where:{seasonId:season.id,teamId:selectedTeam.id}}):0;const active=rows.filter(r=>r.appearances>0).length;const injuries=rows.filter(r=>r.player.injuries.length>0).length;const avgAge=rows.length?round(rows.reduce((n,r)=>n+(r.player.age??0),0)/rows.filter(r=>r.player.age).length):0;
 const href=(extra:Record<string,string|number>)=>`/players?${new URLSearchParams({league:String(competition.apiId),...(selectedTeam?{team:String(selectedTeam.id)}:{}),position,...Object.fromEntries(Object.entries(extra).map(([k,v])=>[k,String(v)]))})}`;
 return <PageShell><main className={styles.page}>
  <header className={styles.hero}><div><p className={styles.eyebrow}>OYUNCU VERİ MERKEZİ · {ACTIVE_SEASON_YEAR}</p><h1>Kadro ve sezon performansı</h1><p>API-Football’dan gelen biyografi, süre, gol, asist, şut, pas, mücadele, faul, kart, penaltı ve kaleci verileri tek profilde.</p></div><div className={styles.fresh}><span><strong>{allCount}</strong> kayıtlı oyuncu</span><span><strong>{rows.length}</strong> gösteriliyor</span></div></header>
  <FootballDirectoryNav pathname="/players" selected={competition.apiId}/>
  <section className={styles.toolbar}><nav>{teams.map(t=><Link key={t.id} href={`/players?league=${competition.apiId}&team=${t.id}`} data-active={selectedTeam?.id===t.id}>{t.name}</Link>)}</nav></section>
  <section className={styles.stats}><article className={styles.stat}><span>Kadro</span><strong>{allCount}</strong></article><article className={styles.stat}><span>Oynayan</span><strong>{active}</strong></article><article className={styles.stat}><span>Eksik / sakat</span><strong>{injuries}</strong></article><article className={styles.stat}><span>Yaş ortalaması</span><strong>{Number.isFinite(avgAge)?avgAge:"–"}</strong></article></section>
  <section className={styles.toolbar}><nav>{positions.map(p=><Link key={p} href={href({position:p})} data-active={position===p}>{p==="ALL"?"Tümü":positionName(p)}</Link>)}</nav><form action="/players"><input type="hidden" name="league" value={competition.apiId}/>{selectedTeam?<input type="hidden" name="team" value={selectedTeam.id}/>:null}<input type="hidden" name="position" value={position}/><input className={styles.search} name="q" defaultValue={q} placeholder="Oyuncu ara…"/></form></section>
  <section className={styles.panel}><header className={styles.panelHead}><h2>{selectedTeam?.name??competition.name}</h2><span className={styles.badge}>Tüm API alanları</span></header>{rows.length===0?<div className={styles.empty}>Bu seçimde oyuncu sezon verisi yok. Pro veri yenilemesini çalıştırın.</div>:<div className={styles.teamCards}>{rows.map(r=><details className={styles.teamCard} key={r.id}><summary><div className={styles.identity}>{r.player.photoUrl?<Image src={r.player.photoUrl} alt="" width={46} height={46}/>:null}<div><strong>{r.player.name}</strong><small>{positionName(r.player.position)} · {r.player.nationality??"Uyruk bekleniyor"}{r.player.injuries[0]?" · EKSİK":""}</small></div></div><b>{r.goals} gol · {r.assists} asist</b></summary><div className={styles.teamCardBody}><div><span>Maç / ilk 11</span><strong>{r.appearances} / {r.starts}</strong></div><div><span>Dakika</span><strong>{r.minutes}</strong></div><div><span>Rating</span><strong>{r.averageRating?.toFixed(2)??"–"}</strong></div><div><span>Şut / isabet</span><strong>{r.shots} / {r.shotsOnTarget}</strong></div><div><span>Pas / isabet</span><strong>{r.passes} / {r.passAccuracy??"–"}%</strong></div><div><span>Kilit pas</span><strong>{r.keyPasses}</strong></div><div><span>Dribbling</span><strong>{r.successfulDribbles}/{r.dribbleAttempts}</strong></div><div><span>İkili mücadele</span><strong>{r.duelsWon}/{r.duels}</strong></div><div><span>Top çalma / kesme</span><strong>{r.tackles}/{r.interceptions}</strong></div><div><span>Faul aldı / yaptı</span><strong>{r.foulsDrawn}/{r.foulsCommitted}</strong></div><div><span>Kart S/K</span><strong>{r.yellowCards}/{r.redCards}</strong></div><div><span>Penaltı gol/kaçan</span><strong>{r.penaltiesScored}/{r.penaltiesMissed}</strong></div><div><span>Kaleci kurtarış</span><strong>{r.saves}</strong></div><div><span>Yediği gol</span><strong>{r.goalsConceded}</strong></div><div><span>Boy / kilo</span><strong>{r.player.heightCm??"–"} cm / {r.player.weightKg??"–"} kg</strong></div><div><span>Forma / yaş</span><strong>{r.player.shirtNumber??"–"} / {r.player.age??"–"}</strong></div></div></details>)}</div>}</section>
 </main></PageShell>;
}
