import Image from "next/image";
import Link from "next/link";
import { PageShell } from "@/components/page-shell";
import { FootballDirectoryNav } from "@/components/football-directory-nav";
import { ACTIVE_SEASON_YEAR } from "@/config/season";
import { prisma } from "@/lib/prisma";
import { firstParam, resolveDirectoryCompetition, round } from "@/lib/football-directory";
import styles from "../football-data.module.css";

type Props={searchParams:Promise<{league?:string|string[];scope?:string|string[];q?:string|string[]}>};
type Scope="ALL"|"HOME"|"AWAY";
type Row={id:number;name:string;logoUrl:string|null;founded:number|null;venueName:string|null;venueCity:string|null;venueCapacity:number|null;venueSurface:string|null;p:number;w:number;d:number;l:number;gf:number;ga:number;pts:number;form:string[];shots:number;shotsOnTarget:number;corners:number;cards:number;statRows:number;players:number};
const scopeOf=(v:string|string[]|undefined):Scope=>{const x=(firstParam(v)??"ALL").toUpperCase();return x==="HOME"||x==="AWAY"?x:"ALL"};

export default async function TeamsPage({searchParams}:Props){
 const params=await searchParams; const competition=resolveDirectoryCompetition(params.league); const scope=scopeOf(params.scope); const query=(firstParam(params.q)??"").trim().toLocaleLowerCase("tr-TR");
 const matches=await prisma.match.findMany({where:{season:{year:ACTIVE_SEASON_YEAR,league:{apiId:competition.apiId}}},orderBy:{kickoffAt:"asc"},include:{homeTeam:true,awayTeam:true,teamStatistics:true}});
 const map=new Map<number,Row>(); const get=(team:typeof matches[number]["homeTeam"])=>{let row=map.get(team.id);if(!row){row={id:team.id,name:team.name,logoUrl:team.logoUrl,founded:team.founded,venueName:team.venueName,venueCity:team.venueCity,venueCapacity:team.venueCapacity,venueSurface:team.venueSurface,p:0,w:0,d:0,l:0,gf:0,ga:0,pts:0,form:[],shots:0,shotsOnTarget:0,corners:0,cards:0,statRows:0,players:0};map.set(team.id,row)}return row};
 for(const m of matches){const h=get(m.homeTeam),a=get(m.awayTeam);if(m.status!=="FINISHED"||m.homeScore===null||m.awayScore===null)continue;const hc=scope!=="AWAY",ac=scope!=="HOME";if(hc){h.p++;h.gf+=m.homeScore;h.ga+=m.awayScore}if(ac){a.p++;a.gf+=m.awayScore;a.ga+=m.homeScore}const hr=m.homeScore>m.awayScore?"W":m.homeScore<m.awayScore?"L":"D",ar=hr==="W"?"L":hr==="L"?"W":"D";if(hc){h.form.push(hr);if(hr==="W"){h.w++;h.pts+=3}else if(hr==="D"){h.d++;h.pts++}else h.l++}if(ac){a.form.push(ar);if(ar==="W"){a.w++;a.pts+=3}else if(ar==="D"){a.d++;a.pts++}else a.l++}for(const s of m.teamStatistics){const r=s.teamId===h.id?h:s.teamId===a.id?a:null;if(!r)continue;r.statRows++;r.shots+=s.shots??0;r.shotsOnTarget+=s.shotsOnTarget??0;r.corners+=s.corners??0;r.cards+=(s.yellowCards??0)+(s.redCards??0)}}
 const season=await prisma.season.findFirst({where:{year:ACTIVE_SEASON_YEAR,league:{apiId:competition.apiId}},select:{id:true}});if(season){const counts=await prisma.playerSeasonStatistic.groupBy({by:["teamId"],where:{seasonId:season.id},_count:{playerId:true}});for(const c of counts){const r=map.get(c.teamId);if(r)r.players=c._count.playerId}}
 const rows=[...map.values()].sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf).filter(r=>!query||r.name.toLocaleLowerCase("tr-TR").includes(query)); const completed=matches.filter(m=>m.status==="FINISHED").length; const coverage=[...map.values()].filter(r=>r.statRows>0).length;
 const href=(s:Scope)=>`/teams?league=${competition.apiId}&scope=${s}`;
 return <PageShell><main className={styles.page}>
  <header className={styles.hero}><div><p className={styles.eyebrow}>TAKIM VERİ MERKEZİ · {ACTIVE_SEASON_YEAR}</p><h1>Puan durumu ve takım profilleri</h1><p>Sonuçlar, form, kadro kapsamı, stat bilgileri ve maç başı gelişmiş takım metrikleri aynı ekranda.</p></div><div className={styles.fresh}><span><strong>{map.size}</strong> takım</span><span><strong>%{map.size?Math.round(coverage/map.size*100):0}</strong> istatistik kapsamı</span></div></header>
  <FootballDirectoryNav pathname="/teams" selected={competition.apiId}/>
  <section className={styles.stats}><article className={styles.stat}><span>Takım</span><strong>{map.size}</strong></article><article className={styles.stat}><span>Biten maç</span><strong>{completed}</strong></article><article className={styles.stat}><span>Lider</span><strong>{rows[0]?.name??"–"}</strong></article><article className={styles.stat}><span>Toplam gol</span><strong>{matches.reduce((n,m)=>n+(m.homeScore??0)+(m.awayScore??0),0)}</strong></article></section>
  <section className={styles.toolbar}><nav><Link href={href("ALL")} data-active={scope==="ALL"}>Genel</Link><Link href={href("HOME")} data-active={scope==="HOME"}>İç saha</Link><Link href={href("AWAY")} data-active={scope==="AWAY"}>Deplasman</Link></nav><form action="/teams"><input type="hidden" name="league" value={competition.apiId}/><input type="hidden" name="scope" value={scope}/><input className={styles.search} name="q" defaultValue={firstParam(params.q)} placeholder="Takım ara…"/></form></section>
  <section className={styles.panel}><header className={styles.panelHead}><h2>{competition.name} sıralaması</h2><span className={styles.badge}>{scope==="ALL"?"Genel":scope==="HOME"?"İç saha":"Deplasman"}</span></header><div className={styles.scroll}><div className={styles.table}><div className={`${styles.tableRow} ${styles.tableHead}`}><span>#</span><span>Takım</span><span>O</span><span>G</span><span>B</span><span>M</span><span>AG</span><span>YG</span><span>AV</span><span>P</span><span>Form</span></div>{rows.map((r,i)=><div className={styles.tableRow} key={r.id}><strong>{i+1}</strong><div className={styles.identity}>{r.logoUrl?<Image src={r.logoUrl} alt="" width={30} height={30}/>:null}<div><strong>{r.name}</strong><small>{r.venueName??"Stat bilgisi bekleniyor"}</small></div></div><span>{r.p}</span><span>{r.w}</span><span>{r.d}</span><span>{r.l}</span><span>{r.gf}</span><span>{r.ga}</span><span>{r.gf-r.ga>0?"+":""}{r.gf-r.ga}</span><strong>{r.pts}</strong><span className={styles.form}>{r.form.slice(-5).map((f,j)=><i key={j}>{f}</i>)}</span></div>)}</div></div></section>
  <section className={styles.panel}><header className={styles.panelHead}><h2>Tüm takım verileri</h2><span className={styles.badge}>Açılır kartlar</span></header><div className={styles.teamCards}>{rows.map(r=><details className={styles.teamCard} key={r.id}><summary><div className={styles.identity}>{r.logoUrl?<Image src={r.logoUrl} alt="" width={36} height={36}/>:null}<div><strong>{r.name}</strong><small>{r.players} oyuncu · {r.venueCity??"şehir bekleniyor"}</small></div></div><b>Detay +</b></summary><div className={styles.teamCardBody}><div><span>Kuruluş</span><strong>{r.founded??"–"}</strong></div><div><span>Stat kapasitesi</span><strong>{r.venueCapacity?.toLocaleString("tr-TR")??"–"}</strong></div><div><span>Zemin</span><strong>{r.venueSurface??"–"}</strong></div><div><span>Maç başı puan</span><strong>{r.p?round(r.pts/r.p,2):"–"}</strong></div><div><span>Maç başı şut</span><strong>{r.statRows?round(r.shots/r.statRows):"–"}</strong></div><div><span>İsabetli şut</span><strong>{r.statRows?round(r.shotsOnTarget/r.statRows):"–"}</strong></div><div><span>Korner</span><strong>{r.statRows?round(r.corners/r.statRows):"–"}</strong></div><div><span>Kart</span><strong>{r.statRows?round(r.cards/r.statRows):"–"}</strong></div></div></details>)}</div></section>
 </main></PageShell>;
}
